<?php

namespace App\DataFixtures\ORM;


use App\Entity\User;
use Faker\Factory;

class LoadUser extends \Doctrine\Bundle\FixturesBundle\Fixture
{
    public function load(\Doctrine\Common\Persistence\ObjectManager $manager){

        $faker = Factory::create();

        $players = [
            $faker->name => 'shotgun',
            $faker->name => 'shotgun',
            $faker->name => 'shotgun',
            $faker->name => 'shotgun',
            $faker->name => 'sniper',
            $faker->name => 'sniper',
            $faker->name => 'm4',
            $faker->name => 'm4',
            $faker->name => 'm4',
            $faker->name => 'handgun',
            $faker->name => 'handgun',
            $faker->name => 'handgun',
        ];

        foreach ($players as $name => $weapon){
            $player = new User();
            $player->setName($name);
            $player->setCurrentWeapon($this->getReference($weapon));

            $manager->persist($player);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return [LoadWeapon::class]; // TODO: Change the autogenerated stub
    }
}